#!/usr/bin/env python3
"""Detect unintended visual change across the example library.

The layout gate measures whether a slide is *balanced*. It cannot tell you that a refactor moved a
colour, shrank a heading, or dropped a border — the geometry can be identical while the slide looks
wrong. That makes it the wrong regression net for CSS work, which is exactly when a net is needed.

This captures a compact fingerprint of every example's render and compares later renders against it.
The fingerprint is a grid of mean RGB values, so it is insensitive to antialiasing jitter but does
catch a changed colour, a moved block, or a lost element. It is small enough to commit, so the
baseline survives across machines and sessions.

Usage:
    python scripts/visual_baseline.py capture            # record the current look as the baseline
    python scripts/visual_baseline.py diff               # compare the current render against it
    python scripts/visual_baseline.py diff --tolerance 3 # allow slightly more drift

Exit codes: 0 = no drift beyond tolerance · 1 = drift found · 2 = could not run.
"""

from __future__ import annotations

import argparse
import json
import sys
import platform
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))
from validate_layout import decode_png, find_browsers, render_with_any  # noqa: E402
from slide_html import slides as html_slides
from example_files import collect

ROOT = Path(__file__).resolve().parents[1]
BASELINE = ROOT / "system" / "visual-baseline.json"
GRID_W, GRID_H = 32, 18          # fingerprint resolution over the 16:9 canvas
# A mean alone is not enough. Recolouring an accent moves few pixels, so the mean barely shifts
# while the slide looks materially different — an early version of this script missed exactly that.
# The peak per-cell delta is what catches a localised change, so both are checked.
DEFAULT_TOLERANCE = 2.0          # mean per-channel difference that still counts as "unchanged"
DEFAULT_PEAK = 12.0              # ...and no single cell may shift more than this
RENDER_SCALE = 0.25              # 1920x1080 layout rendered to 480x270; plenty for a fingerprint


def fingerprint(png: bytes) -> list[int]:
    """Mean RGB per grid cell, flattened. Robust to antialiasing, sensitive to real change."""
    width, height, channels, pixels = decode_png(png)
    cell_w = max(1, width // GRID_W)
    cell_h = max(1, height // GRID_H)
    out: list[int] = []
    for row in range(GRID_H):
        y0 = row * cell_h
        y1 = height if row == GRID_H - 1 else min(height, y0 + cell_h)
        for col in range(GRID_W):
            x0 = col * cell_w
            x1 = width if col == GRID_W - 1 else min(width, x0 + cell_w)
            r = g = b = n = 0
            for y in range(y0, y1, 2):
                base = y * width * channels
                for x in range(x0, x1, 2):
                    i = base + x * channels
                    r += pixels[i]
                    g += pixels[i + 1]
                    b += pixels[i + 2]
                    n += 1
            n = max(1, n)
            out += [r // n, g // n, b // n]
    return out


def targets(paths: list[Path], include_archives=False) -> list[Path]:
    """Current 16:9 slides only. Frozen history and other page formats are separate evidence."""
    found=[]
    for path in collect(paths,include_archives):
        nodes=html_slides(path.read_text(encoding='utf-8'))
        if len(nodes)==1 and 'poster' not in nodes[0].classes:found.append(path)
    return found


def key_for(slide: Path) -> str:
    try:
        return slide.relative_to(ROOT).as_posix()
    except ValueError:
        return slide.as_posix()


def capture_all(slides: list[Path], browsers: list[str]) -> dict[str, Any]:
    prints: dict[str, list[int]] = {}
    for slide in slides:
        png = render_with_any(slide, browsers, 1920, 1080, RENDER_SCALE)
        prints[key_for(slide)] = fingerprint(png)
    return {
        "$comment": (
            "AUTO-GENERATED by scripts/visual_baseline.py. A per-example render fingerprint used to "
            "catch unintended visual change. Re-capture deliberately when a change is intended."
        ),
        "grid": [GRID_W, GRID_H],
        "renderScale": RENDER_SCALE,
        "environment": {"platform":platform.system(),"note":"Requires comparable Chromium and installed fonts; not a cross-platform pixel guarantee."},
        "slides": prints,
    }


def compare(old: list[int], new: list[int]) -> tuple[float, float]:
    if len(old) != len(new):
        return 255.0, 255.0
    diffs = [abs(a - b) for a, b in zip(old, new)]
    return sum(diffs) / len(diffs), float(max(diffs))


def _main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("action", choices=["capture", "diff"])
    parser.add_argument(
        "slides",
        nargs="*",
        type=Path,
        default=[ROOT / "examples"],
        help="files or directories (default: every .html under examples/, recursively)",
    )
    parser.add_argument("--browser", help="path to chrome.exe / msedge.exe")
    parser.add_argument("--include-archives", action="store_true", help="explicitly include frozen historical slides")
    parser.add_argument("--baseline", type=Path, default=BASELINE)
    parser.add_argument("--tolerance", type=float, default=DEFAULT_TOLERANCE,
                        help="max mean per-channel drift")
    parser.add_argument("--peak", type=float, default=DEFAULT_PEAK,
                        help="max drift for any single grid cell (catches localised recolouring)")
    args = parser.parse_args()

    try:
        browsers = find_browsers(args.browser)
    except Exception as exc:  # noqa: BLE001 - surface any startup problem the same way
        print(f"visual baseline: {exc}", file=sys.stderr)
        return 2

    slides = targets([Path(p) for p in args.slides],args.include_archives)
    if not slides:
        print("visual baseline: no slides found", file=sys.stderr)
        return 2

    if args.action == "capture":
        data = capture_all(slides, browsers)
        if args.baseline.is_file():
            stored=json.loads(args.baseline.read_text(encoding='utf-8'))
            data['slides']={**stored['slides'],**data['slides']}
        # committed file: keep it compact rather than pretty
        args.baseline.write_text(
            json.dumps(data, separators=(",", ":")) + "\n", encoding="utf-8", newline="\n"
        )
        print(f"captured {len(slides)} current fingerprints -> {args.baseline} (other entries preserved)")
        return 0

    if not args.baseline.is_file():
        print("visual baseline: no baseline recorded yet — run `capture` first", file=sys.stderr)
        return 2
    base = json.loads(args.baseline.read_text(encoding="utf-8"))
    stored = base["slides"]

    changed: list[tuple[str, float, float]] = []
    missing: list[str] = []
    for slide in slides:
        key = key_for(slide)
        if key not in stored:
            missing.append(key)
            continue
        png = render_with_any(slide, browsers, 1920, 1080, RENDER_SCALE)
        mean, peak = compare(stored[key], fingerprint(png))
        if mean > args.tolerance or peak > args.peak:
            changed.append((key, mean, peak))

    for key, mean, peak in sorted(changed, key=lambda c: -c[1]):
        print(f"CHANGED  mean {mean:6.2f}  peak {peak:5.0f}  {key}")
    for key in missing:
        print(f"NEW      (no baseline entry)          {key}")

    if changed or missing:
        print(
            f"\nvisual drift: {len(changed)} changed, {len(missing)} missing baseline, of {len(slides)} slides; tolerance "
            f"{args.tolerance}. If the change was intended, re-run `capture`.",
            file=sys.stderr,
        )
        return 1
    print(f"\nno visual drift: {len(slides)} slides match the baseline (tolerance {args.tolerance})")
    return 0


def main() -> int:
    try:
        return _main()
    except Exception as exc:
        print(f"visual baseline could not run: {exc}",file=sys.stderr)
        return 2


if __name__ == "__main__":
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except AttributeError:
        pass
    raise SystemExit(main())
