"""AUTO-GENERATED by scripts/compile_system.py. DO NOT EDIT."""

FOUNDATIONS = {
    'font-cjk': '"Noto Sans TC","PingFang TC","Microsoft JhengHei",sans-serif',
    'font-latin': 'Arial,"Helvetica Neue",sans-serif',
    'ls-cjk': '0.05em',
    'ls-latin': '0',
    'lh': '1.5',
    'fs-h1': '50px',
    'fs-metric': '56px',
    'fs-section': '30px',
    'fs-eyebrow': '22px',
    'fs-q': '20px',
    'fs-pill': '18px',
    'fs-body': '17px',
    'fs-caption': '14px',
    'fs-ui-1': '11px',
    'fs-ui-2': '12px',
    'fs-ui-3': '13px',
    'fs-ui-4': '14px',
    'fs-ui-5': '16px',
    'lh-ui-1': '15px',
    'lh-ui-2': '16px',
    'lh-ui-3': '18px',
    'lh-ui-4': '19px',
    'lh-ui-5': '22px',
    'fw-regular': '400',
    'fw-medium': '500',
    'fw-bold': '700',
    's0': '4px',
    's1': '8px',
    's2': '12px',
    's3': '16px',
    's4': '24px',
    's5': '32px',
    's6': '48px',
    's7': '64px',
    's8': '80px',
    's9': '96px',
    'pad-y': '80px',
    'pad-x': '96px',
    'gutter': '32px',
    'gap-section': '48px',
    'pad-card': '48px',
    'r-card': '24px',
    'r-pill': '999px',
    'r-sm': '18px',
}

THEME_TOKENS = {
    'light': {
        'canvas': 'FBFBFE',
        'backdrop': 'CDD2DC',
        'surface': 'F1F4F9',
        'chip': 'FFFFFF',
        'ink': '2B3040',
        'muted': '7C7E92',
        'muted-soft': 'DCE0EB',
        'accent': '7077FB',
        'accent-soft': 'E7E8FC',
        'on-accent': 'FFFFFF',
        'band-fill': '2B3040',
        'band-tag': 'B7BCD0',
        'donut-3': 'C2C6D4',
        'pos': '2FB67A',
        'pos-soft': 'DCF3E8',
        'neg': 'E5556E',
        'neg-soft': 'FBE2E7',
        'warn': 'E08A1E',
        'warn-soft': 'FBEED7',
        'shadow-card': '0 4px 16px rgba(17,20,40,.05)',
        'shadow-pop': '0 10px 28px rgba(17,20,40,.10)',
        'shadow-img': '0 2px 6px rgba(17,20,40,.05), 0 16px 38px rgba(17,20,40,.13)',
    },
    'dark': {
        'canvas': '1B1B20',
        'backdrop': '111116',
        'surface': '2C2C33',
        'chip': '34343C',
        'ink': 'FFFFFF',
        'muted': '9A9CA8',
        'muted-soft': '454652',
        'accent': '4D77FF',
        'accent-soft': '2A3358',
        'on-accent': 'FFFFFF',
        'band-fill': '23242C',
        'band-tag': 'B7BCD0',
        'donut-3': '5E6070',
        'pos': '34D399',
        'pos-soft': '173A30',
        'neg': 'F26D82',
        'neg-soft': '3A1F26',
        'warn': 'F2B04E',
        'warn-soft': '3A2E18',
        'shadow-card': '0 4px 16px rgba(0,0,0,.18)',
        'shadow-pop': '0 10px 28px rgba(0,0,0,.26)',
        'shadow-img': '0 2px 8px rgba(0,0,0,.3), 0 20px 46px rgba(0,0,0,.5)',
    },
}

HYPERTOKEN_VALUES = {
    'surface.card': {
        'background': {'token': 'surface'},
        'border-radius': {'token': 'r-card'},
        'padding': {'token': 'pad-card'},
    },
    'text.heading': {
        'font-size': {'token': 'fs-h1'},
        'font-weight': {'value': '700'},
        'color': {'token': 'ink'},
        'margin': {'value': '0'},
        'line-height': {'token': 'lh'},
    },
    'text.supporting': {
        'font-size': {'token': 'fs-body'},
        'color': {'token': 'muted'},
        'margin': {'value': '0'},
    },
    'layout.stack.card': {
        'position': {'value': 'relative'},
        'display': {'value': 'flex'},
        'flex-direction': {'value': 'column'},
        'gap': {'token': 's4'},
    },
    'image.floating': {
        'box-shadow': {'token': 'shadow-img'},
    },
    'layout.grid': {
        'display': {'value': 'grid'},
    },
    'layout.column': {
        'display': {'value': 'flex'},
        'flex-direction': {'value': 'column'},
    },
    'layout.row': {
        'display': {'value': 'flex'},
    },
    'layout.center-items': {
        'align-items': {'value': 'center'},
    },
    'layout.center-content': {
        'justify-content': {'value': 'center'},
    },
    'surface.panel': {
        'background': {'token': 'surface'},
        'border-radius': {'token': 'r-card'},
    },
    'surface.neutral': {
        'background': {'token': 'surface'},
    },
    'surface.soft': {
        'background': {'token': 'accent-soft'},
    },
    'surface.accent': {
        'background': {'token': 'accent'},
    },
    'surface.muted': {
        'background': {'token': 'muted-soft'},
    },
    'text.primary': {
        'color': {'token': 'ink'},
    },
    'text.secondary': {
        'color': {'token': 'muted'},
    },
    'text.accent': {
        'color': {'token': 'accent'},
    },
    'text.on-accent': {
        'color': {'token': 'on-accent'},
    },
    'text.bold': {
        'font-weight': {'value': '700'},
    },
    'type.numeric': {
        'font-family': {'token': 'font-latin'},
    },
    'geometry.relative': {
        'position': {'value': 'relative'},
    },
    'image.cover': {
        'display': {'value': 'block'},
        'width': {'value': '100%'},
        'height': {'value': '100%'},
        'object-fit': {'value': 'cover'},
    },
    'table.collapse': {
        'border-collapse': {'value': 'collapse'},
        'width': {'value': '100%'},
    },
    'image.card-elevation': {
        'box-shadow': {'token': 'shadow-card'},
    },
}

def _compat_tokens(mode):
    return {name.replace('-', '_'): value for name, value in THEME_TOKENS[mode].items()}

LIGHT = _compat_tokens('light')
DARK = _compat_tokens('dark')

def apply_tone(token_map, tone=None):
    result = dict(token_map)
    if tone == 'pos':
        result['accent'], result['accent_soft'] = result['pos'], result['pos_soft']
    if tone == 'neg':
        result['accent'], result['accent_soft'] = result['neg'], result['neg_soft']
    if tone == 'warn':
        result['accent'], result['accent_soft'] = result['warn'], result['warn_soft']
    return result

def tokens(mode):
    if mode not in THEME_TOKENS:
        raise ValueError(f'unknown mode: {mode}')
    return _compat_tokens(mode)

def hypertoken(name, mode):
    if name not in HYPERTOKEN_VALUES:
        raise KeyError(name)
    if mode not in THEME_TOKENS:
        raise ValueError(f'unknown mode: {mode}')
    pool = {**FOUNDATIONS, **THEME_TOKENS[mode]}
    result = {}
    for prop, record in HYPERTOKEN_VALUES[name].items():
        result[prop] = pool[record['token']] if 'token' in record else record['value']
    return result

RECIPE_SLOTS = {
    'as-is-to-be': {'root': ['layout.grid'], 'column': ['layout.column'], 'label': ['text.primary'], 'supporting': ['text.secondary']},
    'centered-question-evidence': {'root': ['layout.grid'], 'heading': ['text.heading'], 'evidence': ['surface.panel', 'layout.column'], 'supporting': ['text.secondary']},
    'citation-card': {'root': ['surface.panel', 'layout.column'], 'finding': ['text.primary'], 'source': ['text.secondary']},
    'comparison-table': {'root': ['table.collapse'], 'value': ['text.secondary'], 'focus': ['text.accent', 'text.bold']},
    'cta-buttons': {'root': ['layout.row'], 'button': ['text.bold'], 'secondary': ['text.primary']},
    'delta-metric': {'root': ['layout.column'], 'heading': ['layout.row'], 'value': ['text.accent', 'type.numeric'], 'label': ['text.primary']},
    'editorial-explainer-stage': {'root': ['layout.grid'], 'stage': ['surface.neutral'], 'artwork': ['image.cover'], 'supporting': ['text.secondary']},
    'evidence-card': {'root': ['surface.panel', 'layout.column'], 'value': ['text.primary', 'type.numeric'], 'supporting': ['text.secondary']},
    'feature-card': {'root': ['surface.panel', 'layout.row'], 'icon': ['surface.soft', 'layout.grid'], 'heading': ['text.primary'], 'supporting': ['text.secondary']},
    'feature-grid': {'root': ['layout.grid'], 'item': ['surface.panel', 'layout.row'], 'heading': ['text.primary'], 'supporting': ['text.secondary']},
    'feature-showcase': {'root': ['layout.grid'], 'heading': ['text.heading'], 'area': ['layout.column'], 'supporting': ['text.secondary'], 'mockup': ['image.card-elevation']},
    'geo-map': {'root': ['layout.row'], 'annotation': ['layout.column'], 'value': ['text.primary', 'type.numeric'], 'label': ['text.secondary']},
    'hero-radial': {'root': ['layout.grid'], 'side': ['surface.panel', 'layout.column'], 'stage': ['layout.grid', 'geometry.relative'], 'core': ['surface.accent', 'text.on-accent']},
    'icon-label-row': {'root': ['layout.column'], 'row': ['layout.grid'], 'icon': ['surface.soft', 'layout.grid'], 'label': ['text.primary']},
    'idea-evidence': {'root': ['layout.grid'], 'panel': ['surface.panel', 'layout.column'], 'value': ['text.accent', 'type.numeric'], 'supporting': ['text.secondary']},
    'interview-affinity': {'root': ['layout.grid'], 'participant': ['surface.panel', 'layout.column'], 'heading': ['text.primary'], 'insight': ['surface.soft', 'text.primary']},
    'keyword-cards': {'root': ['layout.grid'], 'item': ['surface.panel', 'layout.column'], 'heading': ['text.primary'], 'supporting': ['text.secondary']},
    'level-slider': {'root': ['layout.column'], 'row': ['layout.grid'], 'fill': ['surface.accent'], 'label': ['text.primary']},
    'linked-circles': {'root': ['layout.row', 'layout.center-items', 'layout.center-content'], 'circle': ['layout.column', 'surface.soft'], 'label': ['text.accent', 'type.numeric'], 'supporting': ['text.primary']},
    'logo-row': {'root': ['layout.row', 'layout.center-items'], 'logo': ['layout.grid', 'surface.neutral', 'text.secondary']},
    'metric-card': {'root': ['surface.panel', 'layout.column'], 'heading': ['text.primary', 'text.bold'], 'supporting': ['text.secondary'], 'icon': ['text.accent']},
    'numbered-row': {'root': ['layout.grid'], 'badge': ['surface.accent', 'text.on-accent', 'layout.grid'], 'heading': ['text.primary'], 'chart': ['surface.panel']},
    'numbered-rows': {'root': ['layout.grid'], 'badge': ['surface.accent', 'text.on-accent', 'layout.grid'], 'supporting': ['text.secondary'], 'chart': ['surface.panel']},
    'painpoint-evidence': {'root': ['layout.grid'], 'panel': ['layout.column'], 'finding': ['text.primary'], 'quote': ['surface.panel', 'text.primary']},
    'persona-cards': {'root': ['layout.grid'], 'persona': ['layout.column'], 'heading': ['text.primary'], 'supporting': ['text.secondary']},
    'pie-donut': {'root': ['layout.grid', 'geometry.relative'], 'value': ['text.primary', 'type.numeric'], 'legend': ['layout.column']},
    'positioning-matrix': {'root': ['layout.grid'], 'map': ['surface.panel', 'geometry.relative'], 'label': ['text.secondary'], 'focus': ['text.accent']},
    'problem-solution': {'root': ['layout.grid'], 'panel': ['layout.column'], 'heading': ['text.primary'], 'supporting': ['text.secondary']},
    'product-hero': {'root': ['layout.grid'], 'heading': ['text.primary'], 'supporting': ['text.secondary'], 'value': ['text.primary', 'type.numeric']},
    'qual-quant-split': {'root': ['layout.grid'], 'quotes': ['layout.column'], 'stats': ['layout.column'], 'quote': ['surface.panel', 'text.primary']},
    'quote-bubble': {'root': ['surface.panel', 'text.primary'], 'source': ['text.secondary']},
    'ranked-list': {'root': ['layout.column'], 'row': ['layout.grid', 'surface.panel'], 'heading': ['text.primary'], 'supporting': ['text.secondary']},
    'research-flow': {'root': ['layout.grid'], 'evidence': ['surface.card', 'layout.stack.card'], 'finding': ['text.primary'], 'source': ['text.secondary']},
    'results-grid': {'root': ['layout.grid'], 'hero': ['text.accent', 'type.numeric'], 'supporting': ['layout.column'], 'value': ['text.primary', 'type.numeric']},
    'service-flow': {'root': ['surface.panel', 'layout.row'], 'node': ['layout.column'], 'label': ['text.primary'], 'branch': ['layout.column']},
    'stat-bar': {'root': ['layout.column'], 'label': ['text.primary'], 'track': ['surface.muted'], 'fill': ['surface.accent', 'text.on-accent']},
    'survey-stack': {'root': ['layout.grid'], 'card': ['surface.card', 'layout.stack.card'], 'supporting': ['text.supporting'], 'bars': ['layout.column']},
    'taglist': {'root': ['layout.row'], 'chip': ['text.primary']},
    'terminology-card': {'root': ['surface.panel', 'layout.column'], 'artwork': ['surface.soft', 'layout.grid'], 'term': ['text.accent'], 'definition': ['text.secondary']},
    'terminology-cards': {'root': ['layout.grid'], 'card': ['surface.panel', 'layout.column'], 'term': ['text.accent'], 'definition': ['text.secondary']},
    'timeline': {'root': ['layout.column'], 'axis': ['layout.grid', 'text.secondary'], 'phases': ['layout.grid'], 'phase': ['layout.column']},
    'ui-mockup': {'root': ['surface.panel'], 'skeleton': ['surface.muted'], 'highlight': ['surface.soft']},
    'use-case-cards': {'root': ['layout.grid'], 'item': ['layout.column'], 'card': ['surface.panel', 'layout.grid'], 'supporting': ['text.secondary']},
    'value-points': {'root': ['layout.grid'], 'point': ['layout.column'], 'card': ['surface.panel'], 'supporting': ['text.secondary']},
}

def recipe(name, slot, mode):
    result = {}
    for ref in RECIPE_SLOTS[name][slot]:
        result.update(hypertoken(ref, mode))
    return result
