"""AUTO-GENERATED by scripts/compile_system.py. DO NOT EDIT."""

FOUNDATIONS = {
    'font-cjk': '"Noto Sans TC","PingFang TC","Microsoft JhengHei",sans-serif',
    'font-latin': 'Arial,"Helvetica Neue",sans-serif',
    'ls-cjk': '0.05em',
    'ls-latin': '0',
    'lh': '1.5',
    'fs-h1': '50px',
    'fs-metric': '56px',
    'fs-section': '30px',
    'fs-eyebrow': '22px',
    'fs-q': '20px',
    'fs-pill': '18px',
    'fs-body': '17px',
    'fs-caption': '14px',
    's0': '4px',
    's1': '8px',
    's2': '12px',
    's3': '16px',
    's4': '24px',
    's5': '32px',
    's6': '48px',
    's7': '64px',
    's8': '80px',
    's9': '96px',
    'pad-y': '80px',
    'pad-x': '96px',
    'gutter': '32px',
    'gap-section': '48px',
    'pad-card': '48px',
    'r-card': '24px',
    'r-pill': '999px',
    'r-sm': '18px',
}

THEME_TOKENS = {
    'light': {
        'canvas': 'FBFBFE',
        'surface': 'F1F4F9',
        'chip': 'FFFFFF',
        'ink': '2B3040',
        'muted': '7C7E92',
        'muted-soft': 'DCE0EB',
        'accent': '7077FB',
        'accent-soft': 'E7E8FC',
        'on-accent': 'FFFFFF',
        'band-fill': '2B3040',
        'band-tag': 'B7BCD0',
        'donut-3': 'C2C6D4',
        'pos': '2FB67A',
        'pos-soft': 'DCF3E8',
        'neg': 'E5556E',
        'neg-soft': 'FBE2E7',
        'warn': 'E08A1E',
        'warn-soft': 'FBEED7',
        'shadow-card': '0 4px 16px rgba(17,20,40,.05)',
        'shadow-pop': '0 10px 28px rgba(17,20,40,.10)',
        'shadow-img': '0 2px 6px rgba(17,20,40,.05), 0 16px 38px rgba(17,20,40,.13)',
    },
    'dark': {
        'canvas': '1B1B20',
        'surface': '2C2C33',
        'chip': '34343C',
        'ink': 'FFFFFF',
        'muted': '9A9CA8',
        'muted-soft': '454652',
        'accent': '4D77FF',
        'accent-soft': '2A3358',
        'on-accent': 'FFFFFF',
        'band-fill': '23242C',
        'band-tag': 'B7BCD0',
        'donut-3': '5E6070',
        'pos': '34D399',
        'pos-soft': '173A30',
        'neg': 'F26D82',
        'neg-soft': '3A1F26',
        'warn': 'F2B04E',
        'warn-soft': '3A2E18',
        'shadow-card': '0 4px 16px rgba(0,0,0,.18)',
        'shadow-pop': '0 10px 28px rgba(0,0,0,.26)',
        'shadow-img': '0 2px 8px rgba(0,0,0,.3), 0 20px 46px rgba(0,0,0,.5)',
    },
}

HYPERTOKEN_VALUES = {
    'surface.card': {
        'background': {'token': 'surface'},
        'border-radius': {'token': 'r-card'},
        'padding': {'token': 'pad-card'},
    },
    'text.heading': {
        'font-size': {'token': 'fs-h1'},
        'font-weight': {'value': '700'},
        'color': {'token': 'ink'},
        'margin': {'value': '0'},
        'line-height': {'token': 'lh'},
    },
    'text.supporting': {
        'font-size': {'token': 'fs-body'},
        'color': {'token': 'muted'},
        'margin': {'value': '0'},
    },
    'layout.stack.card': {
        'position': {'value': 'relative'},
        'display': {'value': 'flex'},
        'flex-direction': {'value': 'column'},
        'gap': {'token': 's4'},
    },
    'image.floating': {
        'box-shadow': {'token': 'shadow-img'},
    },
}

def _compat_tokens(mode):
    return {name.replace('-', '_'): value for name, value in THEME_TOKENS[mode].items()}

LIGHT = _compat_tokens('light')
DARK = _compat_tokens('dark')

def apply_tone(token_map, tone=None):
    result = dict(token_map)
    if tone == 'pos':
        result['accent'], result['accent_soft'] = result['pos'], result['pos_soft']
    if tone == 'neg':
        result['accent'], result['accent_soft'] = result['neg'], result['neg_soft']
    if tone == 'warn':
        result['accent'], result['accent_soft'] = result['warn'], result['warn_soft']
    return result

def tokens(mode):
    if mode not in THEME_TOKENS:
        raise ValueError(f'unknown mode: {mode}')
    return _compat_tokens(mode)

def hypertoken(name, mode):
    if name not in HYPERTOKEN_VALUES:
        raise KeyError(name)
    if mode not in THEME_TOKENS:
        raise ValueError(f'unknown mode: {mode}')
    pool = {**FOUNDATIONS, **THEME_TOKENS[mode]}
    result = {}
    for prop, record in HYPERTOKEN_VALUES[name].items():
        result[prop] = pool[record['token']] if 'token' in record else record['value']
    return result
